{% set version = "3.5.8" %}

package:
  name: machine-learning-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/machine-learning-py/machine-learning-py-{{ version }}.tar.gz
  sha256: 7dec5c202072d1b95a220dc9f39035c195df6f9a9e23e623bf6e70d2590c363e
  patches:
    - setup.patch
  
build:
  number: 4
  skip: True  # [win or py>36]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - scipy >=0.7.0
    - gsl >=1.11
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.7.0
    - gsl >=1.11

test:
  imports:
    - mlpy
    - mlpy.bordacount
    - mlpy.fastcluster
    - mlpy.hcluster
    - mlpy.wavelet

about:
  home: https://github.com/richardARPANET/mlpy
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: "mlpy - Machine Learning Py - High-Performance Python Package for Predictive Modeling"

extra:
  recipe-maintainers:
    - npavlovikj
