travis:
  secure:
    BINSTAR_TOKEN: qPzOjbAli3Ew72mmJXESW8BlRVHMQ9MpSYRdWV52SstWEr0LcRbor1CK0uAQMzCRrOg5gvZe9QBqDT3GNYZDM83qLiSNWwt0E+Qsqjig3tHFZBtqmD4G3RhhgvVtMzBgoEDdzz7OHVZTCi/GZJMjl3yd8wCD6n8IFe3HpgKSr1vvwHVJXHbzYRZ58o5WrdDDqpHYvnVBEgZT8n+32tvzgzFoebfZb1ols9d18Y4qbsPDnkGDI0ifnlsRD0PmIpB4LmFnQMpeyH4suply4uLPdcOIG1uqngVFVnbQ2IY1I8AiRatNlTzByxYWzl5Y+MMMoXlUMWBdF90xid1CsPqYRA2uZ4gprzkfmzz9yEyz8npgr/wtj449y1Sd+GHb8sYBdQ0F+rsWmFpf4p1ITovw3Krtl1O82DgGNTSj6u1JY7S8pn7dLskMcn/lsX3Sjq3FTUMOvF08VSQAHf7iM2Eoj9XK5VMf0bCnJXv1WsnfpVxAtf0tw/QV1JLXx107HZJ8LapoPsU+VLRaIjhwVCP6v+1RVtgHTWEc9UqjksTMFf5KnplgUyEyie7jqFMl3tXRI/wfqUPDah9fRuLbFxUAbZO2x6o9xqhLR0ordHEH90JcJxfH5jJaz1ssGtwDUa+1yyi2W0Mgqt1U6kmSnCov20qVf5pDAPof7wbuNNx1e40=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
